In [1]:
import collections
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow as tf

from tensorflow.keras import layers
from keras.layers import Dense
from keras.models import Sequential, Model

Using TensorFlow backend.

In [2]:
#Recuperaci√≥n del Dataset generado anteriormente
dataMeteoCellId = pd.read_csv('tres_semanas_mi_tweet_meteo.csv', index_col=0)
dataMeteoCellId = dataMeteoCellId.iloc[:,4:15]
dataMeteoCellId.describe()

,hour,idx,internet,smsin,smsout,week,weekday,tweet,relativeHumidity,precipitation,temperature
count,3024.000000,3024.000000,3024.000000,3024.000000,3024.000000,3024.000000,3024.000000,3024.000000,3024.000000,3024.000000,3024.000000
mean,11.500000,8315.500000,1883.184312,146.427246,69.256627,49.000000,3.000000,0.156085,60.146495,0.025066,5.464153
std,6.923331,145.516044,990.053311,134.946435,62.076475,0.816632,2.000331,0.748209,33.144768,0.268528,4.398353
min,0.000000,8064.000000,261.785621,0.000000,0.000000,48.000000,0.000000,0.000000,0.000000,0.000000,-29.900000
25%,5.750000,8189.750000,1218.694935,23.220361,25.589508,48.000000,1.000000,0.000000,40.000000,0.000000,2.900000
50%,11.500000,8315.500000,1658.813447,113.045781,56.829623,49.000000,3.000000,0.000000,70.000000,0.000000,5.700000
75%,17.250000,8441.250000,2481.586954,235.320039,101.127651,50.000000,5.000000,0.000000,88.000000,0.000000,8.700000
max,23.000000,8567.000000,9162.618461,795.333182,424.175655,50.000000,6.000000,17.000000,100.000000,8.000000,14.500000

In [3]:
dataMeteoCellId.drop(['idx','smsin', 'smsout', 'week', 'tweet'],axis=1,inplace=True)
dataMeteoCellId

      hour     internet  weekday  relativeHumidity  precipitation  temperature
3456     0  1401.022757        0              79.0            0.0         11.0
3457     0  2016.712148        0              81.0            0.0         10.7
3458     0  1245.468163        0              88.0            0.0          9.3
3459     0  2703.537850        0              90.0            0.0          9.2
3460     0   858.288439        0               0.0            0.0          8.7
...    ...          ...      ...               ...            ...          ...
6475    23  2271.731795        6             100.0            0.0          3.8
6476    23  1713.374630        6              95.0            0.0          2.4
6477    23  2713.216708        6              93.0            0.0          2.8
6478    23   999.341485        6               0.0            0.0          2.8
6479    23  1432.508885        6              98.0            0.0          3.2

[3024 rows x 6 columns]

In [4]:
dataMeteoDL = StandardScaler().fit_transform(dataMeteoCellId)
dataMeteoDL = pd.DataFrame(dataMeteoDL,columns=dataMeteoCellId.columns)

In [5]:
y = dataMeteoDL.iloc[:,1]
dataMeteoDL.drop(['internet'],axis=1,inplace=True)
X = dataMeteoDL

In [6]:
X

          hour  weekday  relativeHumidity  precipitation  temperature
0    -1.661325     -1.5          0.568917      -0.093362     1.258826
1    -1.661325     -1.5          0.629268      -0.093362     1.190608
2    -1.661325     -1.5          0.840498      -0.093362     0.872254
3    -1.661325     -1.5          0.900849      -0.093362     0.849514
4    -1.661325     -1.5         -1.814960      -0.093362     0.735817
...        ...      ...               ...            ...          ...
3019  1.661325      1.5          1.202606      -0.093362    -0.378421
3020  1.661325      1.5          1.051728      -0.093362    -0.696774
3021  1.661325      1.5          0.991376      -0.093362    -0.605816
3022  1.661325      1.5         -1.814960      -0.093362    -0.605816
3023  1.661325      1.5          1.142255      -0.093362    -0.514858

[3024 rows x 5 columns]

In [7]:
y

0      -0.487086
1       0.134892
2      -0.644230
3       0.828732
4      -1.035364
          ...
3019    0.392516
3020   -0.171544
3021    0.838510
3022   -0.892870
3023   -0.455278
Name: internet, Length: 3024, dtype: float64

In [8]:
#X= []
#y = []
#for dataMeteoTweet in dataMeteoCellId.itertuples(index=False):
#    X.append(np.array([dataMeteoTweet.weekday, dataMeteoTweet.hour, dataMeteoTweet.temperature, dataMeteoTweet.precipitation]))
#    y.append(dataMeteoTweet.tweet)

In [9]:
#X = np.array(X)
#y = np.array(y)

In [10]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=10)

In [11]:
Xtrain

          hour  weekday  relativeHumidity  precipitation  temperature
2144  1.372399     -1.5          0.116282      -0.093362    -0.310202
1353 -0.361158     -0.5          0.055931      -0.093362    -1.901970
1625 -0.794547      0.5          0.387863      -0.093362    -1.265263
2990  0.939010      1.5          0.931025      -0.093362    -0.560337
778  -0.361158      1.0         -1.814960      -0.093362    -0.287463
...        ...      ...               ...            ...          ...
2009  1.516862      1.5          0.508566      -0.093362    -0.605816
1180 -1.083473     -1.0         -1.814960      -0.093362    -1.310742
1344 -0.505621     -0.5         -0.607934      -0.093362    -0.787733
527   0.505621      0.0          1.172430      -0.093362     0.485682
1289  1.516862     -1.0         -0.396704      -0.093362    -0.492119

[2116 rows x 5 columns]

In [12]:
#Convert DataFrame to NumPy array
X_train=Xtrain.values
X_test=Xtest.values
y_train=ytrain.values
y_test=ytest.values

In [13]:
model = Sequential()
model.add(Dense(100, input_dim = 5, activation = 'relu'))
model.add(Dense(1,activation='linear'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 100)               600
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 101
=================================================================
Total params: 701
Trainable params: 701
Non-trainable params: 0
_________________________________________________________________

In [14]:
model.compile(optimizer='adam', loss=tf.keras.losses.MeanSquaredError(), metrics=['accuracy'])

In [15]:
history1024 = model.fit(X_train, y_train, epochs=500, batch_size=1024, validation_data=(X_test, y_test), verbose = 1)

Train on 2116 samples, validate on 908 samples
Epoch 1/500

InternalError: 2 root error(s) found.
  (0) Internal:  Blas GEMM launch failed : a.shape=(1024, 5), b.shape=(5, 100), m=1024, n=100, k=5
	 [[node dense_1/MatMul (defined at E:\Python\TensorFlow\lib\site-packages\keras\backend\tensorflow_backend.py:3009) ]]
	 [[loss/dense_2_loss/mean_squared_error/weighted_loss/broadcast_weights/assert_broadcastable/is_valid_shape/else/_1/has_valid_nonscalar_shape/then/_53/has_invalid_dims/concat/_28]]
  (1) Internal:  Blas GEMM launch failed : a.shape=(1024, 5), b.shape=(5, 100), m=1024, n=100, k=5
	 [[node dense_1/MatMul (defined at E:\Python\TensorFlow\lib\site-packages\keras\backend\tensorflow_backend.py:3009) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_keras_scratch_graph_795]

Function call stack:
keras_scratch_graph -> keras_scratch_graph

In [ ]:
y_pred_class=model.predict(X_test)
y_pred_prob=model.predict_proba(X_test)

In [ ]:
y_pred_class[:5]

In [ ]:
y_pred_class=y_pred_class>0.5

In [ ]:
print(y_pred_class[:5])

In [ ]:
y_pred_class.astype(int)[:5]

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_class)

In [ ]:
ytest=pd.DataFrame(y_test,columns=xtrain.columns)